CREATE DATABASE testTaskPb;
USE testTaskPb;
CREATE TABLE Holidays
(
    login nchar(36) NOT NULL,

    DTS   date      NOT NULL,
    DTE   date      NOT NULL,
    CONSTRAINT Holidays_PK PRIMARY KEY (login, DTS)
);
CREATE TABLE Users
(
    login  nchar(36) NOT NULL,
    name   nchar(36),
    Cal_Id int       NOT NULL,
    CONSTRAINT Users_PK PRIMARY KEY (login)
);
CREATE TABLE Calendar
(
    Cal_Id  int       NOT NULL,
    C_YEAR  int       NOT NULL,
    C_MONTH int       NOT NULL,
    C_DAYS  nchar(93) NOT NULL,
    CONSTRAINT PK_CALENDAR PRIMARY KEY (Cal_Id, C_YEAR, C_MONTH)
);
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 1, 'WYYYYYWWYYYYYWWYYYYYWWYYYYYWWYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 2, 'YYYWWYYYYYWWYYYYYWWYYYYYWWYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 3, 'YYYWWYYYYYWWYYYYYWWYYYYYWWYYYYY');
INSERT INTO Calendar

    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 4, 'WWYYYYYWWYYYYYWWYYYYYWWYYYYYWW');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 5, 'YYYYYWWYYYYYWWYYYYYWWYYYYYWWYYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 6, 'YYWWYYYYYWWYYYYYWWYYYYYWWYYYYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 7, 'WWYYYYYWWYYYYYWWYYYYYWWYYYYYWWY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 8, 'YYYYWWYYYYYWWYYYYYWWYYYYYWWYYYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 9, 'YWWYYYYYWWYYYYYWWYYYYYWWYYYYYW');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 10, 'WYYYYYWWYYYYYWWYYYYYWWYYYYYWWYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 11, 'YYYWWYYYYYWWYYYYYWWYYYYYWWYYYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (1, 2023, 12, 'YWWYYYYYWWYYYYYWWYYYYYWWYYYYYWW');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 1, 'YYYYYWWYYYYYWWYYYYYWWYYYYYWWYYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 2, 'YYWWYYYYWYWYYYYYWWYYYYYWWYYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 3, 'YWWYYYYYWWYYYYYWWYYYYYWWYYYYYWW');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 4, 'YYYYYWWYYYYYWWYYYYYWWYYYYYWWYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 5, 'YYYWWYYYYYWWYYYYYWWYYYYYWWYYYYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 6, 'WWYYYYYWWYYYYYWWYYYYYWWYYYYYWW');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 7, 'YYYYYWWYYYYYWWYYYYYWWYYYYYWWYYY');
INSERT INTO Calendar

    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 8, 'YYWWYYYYYWWYYYYYWWYYYYYWWYYYYYW');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 9, 'WYYYYYWWYYYYYWWYYYYYWWYYYYYWWY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 10, 'YYYYWWYYYYYWWYYYYYWWYYYYYWWYYYY');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 11, 'YWWYYYYYWWYYYYYWWYYYYYWWYYYYYW');
INSERT INTO Calendar
    (Cal_Id, C_YEAR, C_MONTH, C_DAYS)
VALUES (2, 2023, 12, 'WYYYYYWWYYYYYWWYYYYYWWYYYYYWWYY');

INSERT INTO Users (login, name, Cal_Id)
VALUES ('user1234', 'John Doe', 1),
       ('user5678', 'Jane Smith', 2);

INSERT INTO Holidays (login, DTS, DTE)
VALUES ('user1234', '2023-01-01', '2023-01-10'),
       ('user1234', '2023-02-15', '2023-02-20'),
       ('user5678', '2023-03-05', '2023-03-15'),
       ('user1234', '2023-02-05', '2023-02-09'),
       ('user1234', '2023-02-12', '2023-02-16');